### ISSUE TITLE
Salt state pip.installed not available in Travis trusty builds

### ISSUE THREAD

**Issue by sdodsley** [salt-formulas/salt-formula-cinder#22]
It appears that the Salt deployment in the Trusty builds in Travis is not correct. 

Get the following error when running a build:
```
       ----------
                 ID: purestorage
           Function: pip.installed
             Result: False
            Comment: State 'pip.installed' was not found in SLS 'cinder.volume'
              Reason: 'pip.installed' is not available.
            Changes: 
```
The change that causes this to fail is the following added in the `cinder\volume.sls` state file:
```
{%- if backend.engine == 'pure' %}
 
 pureclient:
   pkg.installed:
     - names:
       - python-pip
 
 purestorage:
   pip.installed:
     - name: purestorage
     - require:
       - pkg: pureclient
 
 {%- endif %}
```
This change builds fine in Xenial.

The change is in PR#21
